# Generated by Django 4.2.30 on 2026-09-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='tally_name',
            field=models.CharField(blank=True, help_text='Tally product name for integration', max_length=150),
        ),
    ]
