# Generated by Django 4.2.30 on 2026-09-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_barcode_remove_product_selling_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_stock_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
