# Generated by Codex on 2026-09-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_department'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.department'),
        ),
    ]
