# Generated by Django 4.2.30 on 2026-09-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoice_project_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
